kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: influxdb-data
  labels:
    app: jmeter-influxdb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: influxdb-config
  labels:
    app: jmeter-influxdb
data:
  influxdb.conf: |
    [meta]
    dir = "/var/lib/influxdb/meta"

    [data]
    dir = "/var/lib/influxdb/data"
    engine = "tsm1"
    wal-dir = "/var/lib/influxdb/wal"

    # Configure the graphite API
    [[graphite]]
    enabled = true
    bind-address = ":2003" # If not set, is actually set to bind-address.
    database = "jmeter"  # store graphite data in this database
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: jmeter-influxdb
  labels:
    app: jmeter-influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jmeter-influxdb
  template:
    metadata:
      labels:
        app: jmeter-influxdb
    spec:
      containers:
        - image: influxdb
          imagePullPolicy: IfNotPresent
          name: influxdb
          volumeMounts:
          - name: vol-influxdb-data
            mountPath: /var/lib/influxdb
          ports:
            - containerPort: 8083
              name: influx
            - containerPort: 8086
              name: api
            - containerPort: 2003
              name: graphite
          resources:
            requests:
              memory: 256Mi
              cpu: 0.1
            limits:
              memory: 2Gi
              cpu: 2
      volumes:
      - name: vol-influxdb-data
        persistentVolumeClaim:
          claimName: influxdb-data
---
apiVersion: v1
kind: Service
metadata:
  name: jmeter-influxdb
  labels:
    app: jmeter-influxdb
spec:
  ports:
    - port: 8083
      name: http
      targetPort: 8083
    - port: 8086
      name: api
      targetPort: 8086
    - port: 2003
      name: graphite
      targetPort: 2003
  selector:
    app: jmeter-influxdb