# This base is based on Debian Linux
FROM openjdk:8-jdk-slim

ARG JMETER_VERSION=5.1.1

RUN apt-get clean && \
  apt-get update && \
  apt-get -qy install wget telnet iputils-ping unzip

RUN mkdir /jmeter && \
  cd /jmeter/ && \
  wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-$JMETER_VERSION.tgz && \
  tar -xzf apache-jmeter-$JMETER_VERSION.tgz && \
  rm apache-jmeter-$JMETER_VERSION.tgz

# Write JMeter test log to /tmp
RUN cd /jmeter/apache-jmeter-$JMETER_VERSION/ && sed -i "s+\${sys:jmeter.logfile:-jmeter.log}+/tmp/jmeter.log+" bin/log4j2.xml

# Install standard JMeter plugins
RUN cd /jmeter/apache-jmeter-$JMETER_VERSION/ && \
  wget -q -O /tmp/JMeterPlugins-Standard-1.4.0.zip https://jmeter-plugins.org/downloads/file/JMeterPlugins-Standard-1.4.0.zip && \
  unzip -n /tmp/JMeterPlugins-Standard-1.4.0.zip && \
  rm /tmp/JMeterPlugins-Standard-1.4.0.zip

# ELK/Elastic Stack plugins for JMeter
RUN cd /jmeter/apache-jmeter-$JMETER_VERSION/ && \
  wget -q -O /tmp/jmeter.backendlistener.elasticsearch-2.6.1.zip https://jmeter-plugins.org/files/packages/jmeter.backendlistener.elasticsearch-2.6.1.zip && \
  unzip -n /tmp/jmeter.backendlistener.elasticsearch-2.6.1.zip && \
  rm /tmp/jmeter.backendlistener.elasticsearch-2.6.1.zip

# Kafka load-generation plugin for JMeter
RUN wget -q -O /jmeter/apache-jmeter-$JMETER_VERSION/lib/ext/pepper-box-1.0.jar https://github.com/raladev/load/blob/master/JARs/pepper-box-1.0.jar?raw=true

RUN cd /jmeter/apache-jmeter-$JMETER_VERSION/ && \
  wget -q -O /tmp/bzm-parallel-0.7.zip https://jmeter-plugins.org/files/packages/bzm-parallel-0.7.zip && \
  unzip -n /tmp/bzm-parallel-0.7.zip && \
  rm /tmp/bzm-parallel-0.7.zip

ENV JMETER_HOME /jmeter/apache-jmeter-$JMETER_VERSION/
ENV PATH $JMETER_HOME/bin:$PATH
